import {getChatGPTUser} from '@/app/chatgpt-auth';
import {initialize,refreshSources,getCollection,database} from '@/lib/store';
export const dynamic='force-dynamic';
async function authorized(request:Request){const user=await getChatGPTUser();if(!user)return false;const origin=request.headers.get('origin');return !origin||origin===new URL(request.url).origin;}
export async function GET(request:Request){if(!await authorized(request))return Response.json({error:'Sign in to manage listings.'},{status:401});try{await initialize();return Response.json(await getCollection(true));}catch{return Response.json({error:'Listing storage is temporarily unavailable.'},{status:503});}}
export async function POST(request:Request){if(!await authorized(request))return Response.json({error:'Sign in to manage listings.'},{status:401});if(!request.headers.get('content-type')?.includes('application/json'))return Response.json({error:'JSON required'},{status:415});try{const input=await request.json() as Record<string,unknown>;await initialize();if(input.action==='refresh'){await refreshSources(true);}else if(input.action==='update'&&typeof input.id==='string'){
 const patch:Record<string,unknown>={};if(typeof input.title==='string'&&input.title.trim())patch.title=input.title.trim().slice(0,200);if(typeof input.description==='string')patch.description=input.description.slice(0,1200);if(input.price===null||(typeof input.price==='number'&&input.price>=0))patch.price=input.price;if(input.hidden!==undefined&&typeof input.hidden!=='boolean')return Response.json({error:'Invalid visibility'},{status:400});
 const db=database();const existing=await db.prepare('SELECT override FROM listings WHERE id=?').bind(input.id).first<{override:string|null}>();if(!existing)return Response.json({error:'Listing not found'},{status:404});const merged={...(existing.override?JSON.parse(existing.override):{}),...patch};await db.prepare('UPDATE listings SET override=?,hidden=COALESCE(?,hidden) WHERE id=?').bind(JSON.stringify(merged),input.hidden===undefined?null:Number(input.hidden),input.id).run();
 }else return Response.json({error:'Invalid action'},{status:400});return Response.json(await getCollection(true));}catch(error){console.error(error);return Response.json({error:'Changes could not be saved. Please try again.'},{status:503});}}
