'use client';
import {useEffect,useState} from 'react';
import {Plus,ExternalLink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {communitySources} from '@/lib/social.mjs';
const blank={title:'',url:'',category:'Hiking',type:'Activity',start:'',end:'',time:'',venue:'',neighbourhood:'',description:'',distanceKm:'',difficulty:'Unknown'};
export default function SocialOutingForm({onAdded}:{onAdded:()=>void}){
 const [open,setOpen]=useState(false),[form,setForm]=useState(blank),[error,setError]=useState(''),[saving,setSaving]=useState(false),[success,setSuccess]=useState('');
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('add')==='social')setOpen(true);},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const r=await fetch('/api/sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'add-social',...form})});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error||'Could not add this outing.');setSuccess('Outing added to Winnigo.');setOpen(false);setForm(blank);onAdded();}catch(e){setError(e instanceof Error?e.message:'Could not add this outing.');}finally{setSaving(false);}}
 const field=(key:keyof typeof blank)=>({value:form[key],onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value})});
 return <><section className="social-admin"><div><span className="eyebrow">FACEBOOK & INSTAGRAM</span><h2>Bring community outings into Winnigo.</h2><p>Add a post link and the details you can confirm. Hiking Manitoba is checked by the scheduled browser collector. You can also add Facebook and Instagram posts here.</p><a href={communitySources[0].url} target="_blank" rel="noreferrer">Open Hiking Manitoba <ExternalLink size={14}/></a></div><Button onClick={()=>{setOpen(true);setSuccess('');}}><Plus size={17}/> Add social outing</Button></section>{success&&<p role="status" className="success-note">{success}</p>}<Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v);}}><DialogContent className="social-dialog"><DialogTitle>Add a hiking or cycling outing</DialogTitle><DialogDescription>Use the original Facebook or Instagram post. Leave details you cannot confirm blank.</DialogDescription><form onSubmit={submit} className="social-form"><label>Post link<Input required type="url" placeholder="https://www.facebook.com/groups/…/posts/…" {...field('url')}/></label><label>Outing title<Input required maxLength={200} placeholder="Name of the ride, hike, or route" {...field('title')}/></label><div className="form-two"><label>Activity<select {...field('category')}><option>Hiking</option><option>Cycling</option></select></label><label>Schedule<select {...field('type')}><option value="Activity">Route or date not confirmed</option><option value="Event">Outing with a confirmed date</option></select></label></div>{form.type==='Event'&&<><div className="form-two"><label>Start date<Input required type="date" {...field('start')}/></label><label>End date (optional)<Input type="date" min={form.start} {...field('end')}/></label></div><label>Time in Winnipeg<Input placeholder="For example, 9:00 a.m." {...field('time')}/></label></>}<label>Meeting place or trailhead<Input placeholder="Location from the original post" maxLength={200} {...field('venue')}/></label><label>Area<Input placeholder="Neighbourhood or nearby community" maxLength={100} {...field('neighbourhood')}/></label><div className="form-two"><label>Distance (km)<Input type="number" min="0.1" max="2000" step="0.1" placeholder="Unknown" {...field('distanceKm')}/></label><label>Difficulty<select {...field('difficulty')}><option>Unknown</option><option>Easy</option><option>Moderate</option><option>Challenging</option></select></label></div><label>Useful details<Textarea maxLength={1200} placeholder="Summarize the route, pace, surface, registration, or organizer instructions. Use only details suitable to share." {...field('description')}/></label>{error&&<p role="alert" className="notice">{error}</p>}<Button type="submit" disabled={saving}>{saving?'Adding outing…':'Add to Winnigo'}</Button></form></DialogContent></Dialog></>;
}
