'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,MapPin,ArrowUpRight,Bookmark,Compass,CalendarDays,SlidersHorizontal,ArrowRight,X,Leaf,Sun,Users,Ticket,Check,ExternalLink,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import seed from '@/lib/data/listings.json';
import sourceSeed from '@/lib/data/sources.json';
import {localDay} from '@/lib/connectors.mjs';
type Listing={id:string;title:string;type:string;category:string;venue:string;address:string;neighbourhood:string;start?:string;end?:string;time:string;image:string;url:string;sourceName:string;source:string;checkedAt:string;price:number|null;family:boolean;indoor:boolean;description:string;schedule:string;status:string};
const forksImage='https://www.travelmanitoba.com/imager/assets_simpleviewinc_com/simpleview/image/upload/crm/manitoba/2014-Aerial_web_9b9f470e-5056-a36f-23871ced5d43ef8f_ae9217944f0738f696c093bccdcb3e55.jpg';
const leafImage='https://www.assiniboinepark.ca/uploads/public/images/programs-tours/Leaf_Exterior.jpg';
function dateLabel(item:Listing){if(!item.start)return 'Explore year-round';const f=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric'});return f(item.start)+(item.end&&item.end!==item.start?' – '+f(item.end):'')+(item.schedule==='series'?' · Select dates':'');}
export default function Winnigo(){
 const [items,setItems]=useState<Listing[]>(seed as Listing[]),[tab,setTab]=useState('Explore'),[query,setQuery]=useState(''),[quick,setQuick]=useState('Anytime'),[category,setCategory]=useState('All'),[area,setArea]=useState('All neighbourhoods'),[selected,setSelected]=useState<Listing|null>(null),[saved,setSaved]=useState<string[]>([]),[filters,setFilters]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[reports,setReports]=useState(sourceSeed),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[today,setToday]=useState(localDay()),[limit,setLimit]=useState(24);
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('winnigo-saved')||'[]');setSaved(Array.isArray(stored)?stored.filter(x=>typeof x==='string'):[]);}catch{}const timer=setInterval(()=>setToday(localDay()),60000);fetch('/api/listings').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{items:Listing[];sources:typeof sourceSeed;notice?:string}>}).then(d=>{setItems(d.items);setReports(d.sources);if(d.notice)setNotice(d.notice);}).catch(()=>setNotice('Showing our last collected listings. Live updates are temporarily unavailable.')).finally(()=>setLoading(false));return()=>clearInterval(timer);},[]);
 function save(id:string){setSaved(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];try{localStorage.setItem('winnigo-saved',JSON.stringify(next));}catch{setNotice('Your browser could not save this list.');}return next;});}
 const visible=useMemo(()=>items.filter(i=>{
 if(i.status==='hidden'||(i.end&&i.end<today))return false;
 if(tab==='Saved'&&!saved.includes(i.id))return false;if(tab==='Places'&&i.type!=='Place')return false;if(tab==='Events'&&i.type!=='Event')return false;if(tab==='Activities'&&i.type!=='Activity')return false;
 if(category!=='All'&&i.category!==category)return false;if(area!=='All neighbourhoods'&&i.neighbourhood!==area)return false;
 if(query&&!`${i.title} ${i.venue} ${i.category}`.toLowerCase().includes(query.toLowerCase()))return false;
 if(quick==='Free'&&i.price!==0)return false;if(quick==='Family-friendly'&&!i.family)return false;if(quick==='Indoors'&&!i.indoor)return false;
 if(quick==='Today')return i.schedule==='event'&&!!i.start&&i.start<=today&&(i.end||i.start)>=today;
 if(quick==='This weekend'){const d=new Date(today+'T12:00:00Z'),day=d.getUTCDay();const start=new Date(d);start.setUTCDate(d.getUTCDate()+(day===0?-2:day===6?-1:5-day));const end=new Date(start);end.setUTCDate(start.getUTCDate()+2);return i.schedule==='event'&&!!i.start&&i.start<=end.toISOString().slice(0,10)&&(i.end||i.start)>=start.toISOString().slice(0,10);}
 return true;
 }),[items,tab,saved,category,area,query,quick,today]);
 function reset(){setQuery('');setQuick('Anytime');setCategory('All');setArea('All neighbourhoods');}
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Winnigo home"><span className="brand-icon"><Compass size={23}/></span>winnigo<span className="brand-dot">.</span></a><nav aria-label="Main navigation">{['Explore','Events','Places','Activities','Saved'].map(t=><Button key={t} variant="ghost" className={'nav-button '+(tab===t?'active':'')} onClick={()=>{setTab(t);reset();}}>{t==='Saved'&&<Bookmark size={16}/>} {t}{t==='Saved'&&saved.length>0&&<span className="count">{saved.length}</span>}</Button>)}</nav><span className="city"><MapPin size={15}/> Winnipeg, MB</span></header>
 <main><section className="intro"><div><div className="eyebrow">YOUR CITY. YOUR NEXT ADVENTURE.</div><h1>{tab==='Saved'?'Good plans, kept close.':<>A little more <span>Winnipeg.</span></>}</h1><p>{tab==='Saved'?'Your shortlist, saved on this device.':'Find your next good time. Events, local places, and everything in between.'}</p></div><span className="season"><Sun size={19}/> Make room for getting out</span></section>
 <section className="discovery" aria-label="Search and filters"><div className="search-row"><Search size={21}/><Input aria-label="Search events, places, or activities" placeholder="What are you in the mood for?" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<Button variant="ghost" size="icon" aria-label="Clear search" onClick={()=>setQuery('')}><X/></Button>}<div className="search-location"><MapPin size={17}/> Winnipeg</div><Button className="filter-button" variant="outline" onClick={()=>setFilters(true)}><SlidersHorizontal size={16}/> Filters{area!=='All neighbourhoods'?' •':''}</Button></div><div className="quick-filters">{['Anytime','Today','This weekend','Free','Family-friendly','Indoors'].map(q=><Button key={q} variant="ghost" className={'chip '+(quick===q?'chosen':'')} onClick={()=>setQuick(q)}>{q==='This weekend'?<CalendarDays/>:q==='Free'?<Ticket/>:q==='Family-friendly'?<Users/>:q==='Indoors'?<Leaf/>:null}{q}</Button>)}</div></section>
 {tab==='Explore'&&!query&&quick==='Anytime'&&category==='All'&&<section className="feature-grid"><button className="feature-main" onClick={()=>{setTab('Places');setArea('The Forks');}}><img src={forksImage} alt="The Forks at the meeting of Winnipeg’s rivers"/><div className="image-shade"/><div className="feature-copy"><span className="photo-label">THE LOCAL FAVOURITE</span><h2>Meet you at<br/>The Forks.</h2><p>A meeting place. A market. A whole afternoon.</p><span className="feature-link">Find your way there <ArrowUpRight size={20}/></span></div><span className="photo-credit">Photo: Travel Manitoba</span></button><button className="feature-side" onClick={()=>{setCategory('Outdoors');}}><div className="side-image"><img src={leafImage} alt="The Leaf conservatory and gardens at Assiniboine Park"/><span className="photo-label">A BREATH OF FRESH AIR</span></div><span className="side-photo-credit">Photo: Assiniboine Park Conservancy</span><div className="side-copy"><div><span className="eyebrow">A LITTLE NATURE GOES A LONG WAY</span><h2>Take the scenic route.</h2><p>Gardens, green spaces, and room to wander.</p></div><span className="round-arrow"><ArrowUpRight/></span></div></button></section>}
 <section className="results"><div className="results-heading"><div><div className="eyebrow">{tab==='Saved'?'YOUR COLLECTION':'GOOD THINGS ARE HAPPENING'}</div><h2>{tab==='Saved'?'Saved for later':tab==='Places'?'Places worth a visit':tab==='Activities'?'Get out and try something':tab==='Events'?'On around town':'Find your kind of good time'}</h2></div><span className="result-count" aria-live="polite">{visible.length} {visible.length===1?'discovery':'discoveries'}{loading?' · Checking sources…':''}</span></div><div className="categories">{['All','Arts & culture','Outdoors','Family','Food & drink','Music','Experiences'].map(c=><Button variant="ghost" key={c} className={category===c?'selected-category':''} onClick={()=>setCategory(c)}>{c}</Button>)}</div>
 {notice&&<p className="notice" role="status">{notice}</p>}
 <div className="cards">{visible.slice(0,limit).map((i)=><article className="listing-card" key={i.id}><div className="card-image"><button onClick={()=>setSelected(i)} aria-label={'View '+i.title}><img src={i.image||forksImage} alt={i.image?i.title:'The Forks, Winnipeg'} loading="lazy" onError={e=>{e.currentTarget.src=leafImage;}}/><span className="type-badge">{i.type}</span></button><Button size="icon" className={'save-button '+(saved.includes(i.id)?'is-saved':'')} variant="secondary" aria-label={(saved.includes(i.id)?'Unsave ':'Save ')+i.title} onClick={()=>save(i.id)}><Bookmark size={17} fill={saved.includes(i.id)?'currentColor':'none'}/></Button></div><div className="card-body"><div className="card-meta"><span>{i.category}</span><span>{i.price===0?'Free':i.price===null?'See admission':'$'+i.price}</span></div><button className="card-title" onClick={()=>setSelected(i)}><h3>{i.title}</h3></button><p className="card-date"><CalendarDays size={14}/>{dateLabel(i)}</p><p className="card-venue"><MapPin size={14}/>{i.venue}</p><div className="card-bottom"><span>Via {i.sourceName}</span><button aria-label={'Details for '+i.title} onClick={()=>setSelected(i)}><ArrowUpRight size={18}/></button></div></div></article>)}</div>
 {visible.length===0&&<div className="empty"><Compass size={40}/><h3>{tab==='Saved'?'Your next adventure starts here.':'No discoveries with these filters.'}</h3><p>{tab==='Saved'?'Tap the bookmark on a listing to keep it here.':'Try another date or category. Our collection is still growing.'}</p><Button onClick={()=>{reset();if(tab==='Saved')setTab('Explore');}}>Explore all discoveries</Button></div>}
 {visible.length>limit&&<div className="load-more"><Button variant="outline" onClick={()=>setLimit(n=>n+24)}>Show more discoveries <ArrowRight size={16}/></Button><p>Showing {Math.min(limit,visible.length)} of {visible.length}</p></div>}
 </section><section className="source-strip"><div className="source-icon"><Check size={22}/></div><div><h3>Local sources. One place to look.</h3><p>Collected from Winnipeg calendars, with a link back to every source.</p></div><Button variant="ghost" onClick={()=>setSourceOpen(true)}>Meet the sources <ArrowUpRight size={17}/></Button></section></main>
 <footer><a className="brand" href="/">winnigo<span className="brand-dot">.</span></a><p>Go find your Winnipeg.</p><span>Made for the place we call home. <a className="admin-link" href="/admin">Manage listings</a></span></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="detail-dialog">{selected&&<><img className="detail-image" src={selected.image||forksImage} alt={selected.title}/><span className="eyebrow">{selected.category} · {selected.type}</span><DialogTitle className="detail-title">{selected.title}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><div className="detail-facts"><p><CalendarDays/>{dateLabel(selected)}{selected.time?' · '+selected.time:''}</p><p><MapPin/>{selected.address||selected.venue}</p><p><Ticket/>{selected.price===null?'Admission details on the source website':selected.price===0?'Free admission':'$'+selected.price}</p></div>{selected.schedule==='series'&&<p className="notice">This listing covers select dates. Check the organizer’s schedule before you go.</p>}<div className="detail-actions"><Button asChild><a href={selected.url} target="_blank" rel="noreferrer">Visit original listing <ExternalLink size={16}/></a></Button><Button variant="outline" onClick={()=>save(selected.id)}><Bookmark/>{saved.includes(selected.id)?'Saved':'Save'}</Button><Button variant="ghost" asChild><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(selected.venue+' Winnipeg')} target="_blank" rel="noreferrer">Directions <ArrowUpRight/></a></Button></div><p className="source-note">Source: {selected.sourceName} · Checked {new Date(selected.checkedAt).toLocaleDateString('en-CA')}<br/>Times are local to Winnipeg. Details and availability can change.</p></>}</DialogContent></Dialog>
 <Dialog open={filters} onOpenChange={setFilters}><DialogContent><DialogTitle>Make it your kind of outing</DialogTitle><DialogDescription>Choose an area to explore.</DialogDescription><label htmlFor="area">Neighbourhood</label><select id="area" value={area} onChange={e=>setArea(e.target.value)}>{['All neighbourhoods',...new Set(items.map(i=>i.neighbourhood))].map(a=><option key={a}>{a}</option>)}</select><Button onClick={()=>setFilters(false)}>Show discoveries</Button><Button variant="ghost" onClick={()=>{reset();setFilters(false);}}>Reset filters</Button></DialogContent></Dialog>
 <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent><DialogTitle>Connected to the city</DialogTitle><DialogDescription>Our first sources. Listings link back to the people who know them best.</DialogDescription>{reports.map(s=><div className="source-row" key={s.id}><a href={s.url} target="_blank" rel="noreferrer"><strong>{s.name}</strong><ExternalLink size={14}/></a><p>{s.count} collected listings · {s.status==='ok'?'Last checked '+new Date(s.checkedAt).toLocaleDateString('en-CA'):'Update unavailable; using previous listings'}</p></div>)}<p className="source-note">Collection is growing. Some calendars show only a limited date range. Missing details are left unconfirmed.</p></DialogContent></Dialog>
 </div>;
}
